d = {}

name = input("Enter the name : ")
lang = input("Enter the Language: ")
d.update({name : lang})
name = input("Enter the name : ")
lang = input("Enter the Language: ")
d.update({name : lang})
name = input("Enter the name : ")
lang = input("Enter the Language: ")
d.update({name : lang})
name = input("Enter the name : ")
lang = input("Enter the Language: ")
d.update({name : lang})
print(d)
